[tool.poetry]
name = "test-9"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.5"
mkdocs-material = "^9.5"
mkdocs-techdocs-core = "^1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"